export default defineNuxtConfig({
  modules: ['../src/module'],
  devtools: { enabled: true },
  pdf: {
    // provider: 'gotenberg', // Using puppeteer for local development
    provider: 'puppeteer', // Using puppeteer for local development
    components: ['pdf'],
    sharedComponents: ['pdf/partials'],
    enableI18n: true,
    defaultLocale: 'en',
    availableLocales: ['en', 'es', 'fr'],
    i18nMessages: {
      en: {
        invoice: {
          title: 'Invoice',
          billTo: 'Bill To',
          shipTo: 'Ship To',
          invoiceNumber: 'Invoice #',
          issueDate: 'Issue Date',
          dueDate: 'Due Date',
          description: 'Description',
          quantity: 'Qty',
          price: 'Price',
          total: 'Total',
          subtotal: 'Subtotal',
          tax: 'Tax',
          grandTotal: 'Grand Total',
          paymentTerms: 'Payment Terms',
          notes: 'Notes',
          thankYou: 'Thank you for your business!',
        },
        salesReport: {
          title: 'Sales Report',
          period: 'Period',
          totalSales: 'Total Sales',
          totalOrders: 'Total Orders',
          avgOrderValue: 'Avg Order Value',
          performance: 'Performance Rating',
          quarterlyBreakdown: 'Quarterly Breakdown',
          generatedOn: 'Generated on',
        },
      },
      es: {
        invoice: {
          title: 'Factura',
          billTo: 'Facturar a',
          shipTo: 'Enviar a',
          invoiceNumber: 'Factura #',
          issueDate: 'Fecha de emisión',
          dueDate: 'Fecha de vencimiento',
          description: 'Descripción',
          quantity: 'Cant.',
          price: 'Precio',
          total: 'Total',
          subtotal: 'Subtotal',
          tax: 'Impuesto',
          grandTotal: 'Total General',
          paymentTerms: 'Términos de Pago',
          notes: 'Notas',
          thankYou: '¡Gracias por su negocio!',
        },
        salesReport: {
          title: 'Reporte de Ventas',
          period: 'Período',
          totalSales: 'Ventas Totales',
          totalOrders: 'Órdenes Totales',
          avgOrderValue: 'Valor Promedio de Orden',
          performance: 'Calificación de Rendimiento',
          quarterlyBreakdown: 'Desglose Trimestral',
          generatedOn: 'Generado el',
        },
      },
      fr: {
        invoice: {
          title: 'Facture',
          billTo: 'Facturer à',
          shipTo: 'Expédier à',
          invoiceNumber: 'Facture #',
          issueDate: 'Date d\'émission',
          dueDate: 'Date d\'échéance',
          description: 'Description',
          quantity: 'Qté',
          price: 'Prix',
          total: 'Total',
          subtotal: 'Sous-total',
          tax: 'Taxe',
          grandTotal: 'Total Général',
          paymentTerms: 'Conditions de Paiement',
          notes: 'Notes',
          thankYou: 'Merci pour votre entreprise!',
        },
        salesReport: {
          title: 'Rapport de Ventes',
          period: 'Période',
          totalSales: 'Ventes Totales',
          totalOrders: 'Commandes Totales',
          avgOrderValue: 'Valeur Moyenne de Commande',
          performance: 'Évaluation de Performance',
          quarterlyBreakdown: 'Répartition Trimestrielle',
          generatedOn: 'Généré le',
        },
      },
    },
    providers: {
      gotenberg: {
        url: 'http://localhost:4010',
      },
      browserless: {
        url: 'https://chrome.browserless.io',
        apiKey: process.env.BROWSERLESS_API_KEY || '',
      },
      puppeteer: {
        launchOptions: {
          headless: true,
          args: ['--no-sandbox', '--disable-setuid-sandbox'],
          // executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome'
          executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
        },
      },
    },
    customHelpers: {},
    defaultOptions: {
      format: 'A4',
      margin: {
        top: 20,
        bottom: 20,
        left: 20,
        right: 20,
      },
      landscape: false,
      printBackground: true,
      pageBreak: {
        before: ['always'],
        after: ['always'],
        avoid: ['.no-break'],
      },
    },
  },
})
