name: Publish Beta

on:
  push:
    branches: [develop, beta]
  workflow_dispatch:

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: |
          pnpm lint
          pnpm test:unit
      
      - name: Build
        run: pnpm build
      
      - name: Generate beta version
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"
          npm version $BETA_VERSION --no-git-tag-version
          echo "beta_version=$BETA_VERSION" >> $GITHUB_OUTPUT
      
      - name: Publish beta to npm
        run: pnpm publish --tag beta --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create beta release summary
        run: |
          echo "## 🧪 Beta Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Beta Version**: ${{ steps.version.outputs.beta_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Published**: ✅ Successfully published to npm with beta tag" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "npm install @maistik/nuxt-pdf@${{ steps.version.outputs.beta_version }}" >> $GITHUB_STEP_SUMMARY
          echo "# or" >> $GITHUB_STEP_SUMMARY
          echo "npm install @maistik/nuxt-pdf@beta" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY