import { defineEventHandler, readBody, setHeader, createError, isError } from 'h3'
import { useRuntimeConfig } from '#imports'
// Virtual module generated by the module at build time. It exposes the user's
// custom Handlebars helpers as real functions (see src/module.ts).
// @ts-expect-error - resolved by Nitro, not present at module build time.
import { customHelpers } from '#pdf-custom-helpers'
import { compilePdfComponent } from '../../utils/compiler'
import { createPdfProvider } from '../../utils/providers'

export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  const body = await readBody(event)

  // ---- Input validation ----------------------------------------------------
  const template = body?.template
  const ctx = body?.ctx

  if (typeof template !== 'string' || template.length === 0) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Missing or invalid "template"',
    })
  }

  if (!ctx || typeof ctx !== 'object') {
    throw createError({
      statusCode: 400,
      statusMessage: 'Missing or invalid "ctx"',
    })
  }

  const templateSources = config.pdf.templateSources as Record<string, string>
  if (!Object.prototype.hasOwnProperty.call(templateSources, template)) {
    throw createError({
      statusCode: 404,
      statusMessage: `Template "${template}" not found`,
    })
  }

  const { data, options = {}, locale } = ctx as {
    data: Record<string, unknown>
    options?: Record<string, unknown>
    locale?: string
  }
  const mergedOptions = { ...config.pdf.defaultOptions, ...options }

  // Get i18n messages for the locale
  const messages = config.pdf.enableI18n
    ? config.pdf.i18nMessages[locale || config.pdf.defaultLocale] || {}
    : {}

  // ---- Rendering ------------------------------------------------------------
  try {
    // Compile the template
    const html = compilePdfComponent(
      template,
      { data, options: mergedOptions, locale },
      messages,
      templateSources,
      config.pdf.partialSources,
      customHelpers,
    )

    // Create PDF using the configured provider
    const provider = createPdfProvider(config.pdf.provider, config.pdf.providers)
    const pdfBuffer = await provider.generatePdf(html, mergedOptions)

    // Set response headers
    setHeader(event, 'Content-Type', 'application/pdf')
    setHeader(event, 'Content-Length', pdfBuffer.length.toString())

    return pdfBuffer
  }
  catch (error) {
    // Log the full error server-side for debugging, but never leak internal
    // details (stack traces, provider URLs, etc.) to the client.
    // eslint-disable-next-line no-console -- intentional server-side error log
    console.error('PDF generation error:', error)

    // Re-throw HTTP errors we created intentionally.
    if (isError(error)) {
      throw error
    }

    throw createError({
      statusCode: 500,
      statusMessage: 'Failed to generate PDF',
    })
  }
})
